{.$DEFINE debug}
//调试模式

{$DEFINE ClientMon}
//进程守护客户端

{.$DEFINE TrialVersion}
//试用版本

{$DEFINE UseReport}
//报表支持

{.$DEFINE RandomID}
//使用随机编号

{$DEFINE cxLibrary42}
//Ver4.2编译环境

{.$DEFINE EnableBackupDB}
//备用数据库支持
{.$DEFINE EnableDoubleDB}
//双数据库支持

{$DEFINE OnlyInstance}
//只允许一个实例

{.$DEFINE OldTruckProber}
//旧版直连模式车检

{$DEFINE HYReader}
//启用华宜读卡器

{$DEFINE BXFontCard}
//启用仰邦字库卡LED屏
